### PR TITLE
doc updated

### PR DESCRIPTION
**Pull request by fabiof17**
## Description

Plugin ID added in numerous node documentation pages.
Easier to copy/paste when writing python code, instead of hovering on '?' node icon.

### CODE REVIEW

**Comment by devernay** [comment]
Unfortunately, those files are auto generated, so I won't accept this PR. Please file an issue and I'll do the changes in the source.

**Comment by fabiof17** [comment]
I will.
But what did i do wrong ?

**Comment by devernay** [comment]
The plugin rst doc files are generated automatically from md files that are generated by the Natron code, so you cannot make changes to the plugin rst. They are in the repo because generating them requires pandoc 2.3.1, and I don't want to add that to the build requirements.

**Comment by rodlie** [comment]
Btw, pandoc provides static binaries for each release (works on Windows and CentOS6, have not tested macOS compatibility).

**Comment by devernay** [comment]
Of course, and that's what I use - who builds pandoc anyway?
But still I don't think pandoc should be part of the build system. I regenerate the docs when necessary, and that seems to work quite well so far.
I got a problem recently because newer versions of pandoc broke our tables, and had to do a bisection to find the last version of pandoc that works (and it's 2.3.1)

**Comment by rodlie** [comment]
I agree on that, if it works don't fix it ;)

**Pull request closed without merging**
