### PR TITLE
RB-2.4: use qtpy rather than pyside

### PR DESCRIPTION
**Pull request by devernay**
it will ease the transition to Qt5/PySide2
Suggested by https://github.com/NatronGitHub/Natron/issues/256#issuecomment-864160634

The changes in existing pyplugs should be minimal. qtpy is basically a lightweight layer that gives access to Qt4/PySide through the Qt5 API (with class renames, etc).

We have to check that the pyplugs shipped with Natron still work (should be ok).

Existing pyplugs may need to be adapted for qtoy, but that change will be necessary for Qt5 anyway

### CODE REVIEW

**Comment by Songtech-0912** [comment]
@devernay I agree with the change, but let's not merge it until after the Qt5 port is finished (I am working on it at the moment). I think the saying "if it ain't broke, don't fix it" applies here, we don't want to compromise the reliability and functionality of existing PyPlugs if the change is not yet necessary. Why do I say so? After testing the changed `initGui.py` this is the result:

```
Failed to load /home/songtech/.Natron/initGui.py: Traceback (most recent call last):
  File "<string>", line 6, in <module>
ImportError: No module named qtpy.QtGui
```

It's not working, and if this doesn't work, then the PyPlugs aren't going to work as well. Natron's embedded python doesn't have the `qtpy` module by default and won't have until we actually add it.

Of course, once we *do complete* the Qt5 port, it'll be a different story (we'll then need to get QtPy done to keep the PyPlugs working), but right now it's not a change I'm in favor with merging.

**Comment by rodlie** [comment]
> but let's not merge it until after the Qt5 port is finished

Why wait until Qt5?

> It's not working, and if this doesn't work, then the PyPlugs aren't going to work as well. Natron's embedded python doesn't have the qtpy module by default

Then install qtpy ;) This pull request adds qtpy to the build system.

**Comment by Songtech-0912** [comment]
@rodlie Oh ok. If no existing PyPlugs will be broken by this change, go ahead! Then I have no further objections.

**Comment by rodlie** [comment]
>  If no existing PyPlugs will be broken by this change

This will break all plugins as far as I know, but they all need to be changed anyway when we move away from PySide 1.2.

**Comment by Songtech-0912** [comment]
> > If no existing PyPlugs will be broken by this change
> 
> This will break all plugins as far as I know, but they all need to be changed anyway when we move away from PySide 1.2.

Right, so I think my point still stands. The improvement is a positive one, but let's not merge until the Qt5 port is finished. All in favor?

**Comment by rodlie** [comment]
Did a test build on Windows and this PR does not break anything (since we still have PySide 1.2).

**Comment by devernay** [comment]
This won't break all existing plugins. Actually it may even not break any
plugin, if we're lucky. Take a look at qtpy's source code, it's just
importing pyside in a different namespace with a few renames to make them
more qt5-like. Most pyplugs don't use qt directly anyway.

**Comment by rodlie** [comment]
I have some plugins that import PySide directly, they also work fine.

**Comment by bonalex01dev** [comment]
Hi, would this have an impact on my wish to have python (2 or 3) able to process images in Natron? I think @rodlie told me he could make the Python script node available on windows....

**Comment by rodlie** [comment]
@bonalex01dev 

No, this only impacts Python scripts that import PySide/PySide2/PySide6.

I will however make the RunScript node able to run on Windows (then you can process images with whatever you want, in theory), but not until my summer vacation (end of July).

**Comment by bonalex01dev** [comment]
@rodlie Glad to know your vacations are coming soon ... and we may get some benefit out of it :-)

Mine start next week and I hope to give some time to Natron. Do you have some ideas of useful pyplugs/shadertoy that would be very useful ?
Some early tests tend to show that STMap can be very fast in shadertoy. maybe some other nodes too ?!

**Comment by devernay** [comment]
@bonalex01dev Many plugins can benefit from "fast" implementations using shadertoy, but what you lose is control over the RoD, so usually they can only be used in simple workflows. All color correction nodes, and even the merge nodes could be coded that way, but we would have to keep the CPU version for the "general" case.

When developing these, it is important to test with different RoDs for the inputs and the output.

**Comment by bonalex01dev** [comment]
Thanks for the RoD tip. 
Next week I will probably work in the same office as @fabiof17  and I will see with him as I think some community plugins should be checked on this point (remember of some bugs I found).

**Comment by devernay** [comment]
I propose we merge this at the same time we switch to python3.

**Comment by devernay** [comment]
moving PR to 2.5

**Pull request closed without merging**
