### PR TITLE
Update of docs.

### PR DESCRIPTION
**Pull request by magdesign**
Edited: 
composition-projects-setup.rst
composition-projects-readers.rst
composition-merge.rst
composition-transform.rst

### CODE REVIEW

**Comment by magdesign** [comment]
can please someone approve this or give feedback why it will not be approved, thanks!

**Comment by rodlie** [comment]
Please check your commits, example: https://github.com/hellocatfood/Natron/commit/3a7e2ce9e6b69b6ccd47b030f1998ef80554f3b5

I also recommend prefixing commits with ``Docs: my changes``or ``Documentation: my changes``, since some of the commits may be confused with (code) changes in the application.

**Comment by devernay** [comment]
image
I'm pretty sure you didn't actually edit that many files.
What you should do is:
- save your work (these are just the source files / images that you changed)
- fork the main repo, create a branch for this PR
- copy back your work to this branch
- commit *only* these files. The commit message should be explicit and follow the 50/72 style http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
- do a new PR.

**Comment by magdesign** [comment]
thanks, I will do this!

**Pull request closed without merging**
