### PR TITLE
Move docs to sphinx_rtd_theme.

### PR DESCRIPTION
**Pull request by ivangretsky**
All previously used settings and data are left in the repo, just commented out or not used.

Please read the [contribution guidelines](https://github.com/MrKepzie/Natron/blob/master/CONTRIBUTING.md), and be sure we have a [Contributor License Agreement](http://natron.fr/cla) on record with the project.

## Description

Please provide a description of what this PR is meant to fix,
and how it works (if it's not going to be very clear from the code).

### CODE REVIEW

**Comment by ivangretsky** [comment]
When is it going to hit the main docs at https://natron.readthedocs.io/en/rb-2.3/?
Is there some kind of release process for that?

**Comment by devernay** [comment]
It's ok now, we have a searchable doc, at last!
I had to relaunch the compilation on readthedocs, althoufgh RB-2.3 is an active version... Do you know what could be wrong?
I added you the the rtfd project https://readthedocs.org/projects/natron/ can you check if you see anything wrong?

**Comment by ivangretsky** [comment]
Main docs are with the new theme now. Just restarted the build and refreshed the browser cache. Do not know which one actually solved the issue)) Docs for older versions are with the old theme. We could pack port the changes, but is it worth it?

**Comment by devernay** [comment]
Definitely not worth it!

**Pull request merged**
