### PR TITLE
fix issue #568

### PR DESCRIPTION
**Pull request by devernay**
Restoring links is now done in two passes:
1. Save the links during deserialization in the KnobI
2. Restore the links once all nodes were created

### CODE REVIEW

**Comment by devernay** [comment]
@rodlie can you get a chance to try it if you have time, before I merge?
The scenarios to test are:
- saving/loading projects with hard links and clones and group clones (optional: maybe make a small test case that renders correctly only if clones and hard links are loaded OK)
- for the other scenarios it's ok if links are broken during the operation, but Natron shouldn't crash:
   -  copy/paste nodes, groups...
   - make group, expand group (possibly with hard links going in or out of the group

**Comment by rodlie** [comment]
Will test, it's getting late here, so I will do it tomorrow.

**Comment by devernay** [comment]
@rodlie do you have some time to test before I merge?

**Comment by rodlie** [comment]
Yes, will test now (on Windows).

**Comment by rodlie** [comment]
Cloning/copying/duplicate of groups seems to work fine, also saving/loading. The groups are intact. Will test some more...

**Comment by devernay** [comment]
great! can you approve when you're done testing?

**Review by rodlie — APPROVED** [review]
Looks good to me.

**Pull request merged**
