### PR TITLE
Partial merge of rb 2.5

### PR DESCRIPTION
**Pull request by devernay**
There are conflicts when merging RB-2.5into RB-2.6, so I could not do a full merge.
This is just a cherrypick of some of the 18 commits, but those related to:
1. github actions
2. cmake
3. windows packages

were not merged. Here's the full list of missing commits:
- 7ddcfe8afd1f03e428ce6cbc4f7c7737d9923838 @rodlie
- d1c2659dda688459a7b2aeb675718c65880ffd1d @rodlie
- 1fe5e5281f0cb1933d099d192c8f7dc0f9b06acc reviewed by  @acolwell 
- c7767b15044297b52737e5878d395067434bb8d5 @acolwell 
- cc47b65670df85fc9ac5e49e9a3579a5b75bbaaa @acolwell 
- fddb2e75dd535ae8b791aa73678ffbea9446a642 @acolwell 
- 2d14d4e04c9277db728f19b2405e3b9c234a4ab0 @acolwell 

@acolwell or @rodlie could you check what needs to be merged and do a full merge of RB-2.5 into RB-2.6? We should always merge changes from RB-2.x into RB-2.y if x < y, so that RB-2.y is fully ahead of RB-2.x. Hopefully this will not be an issue anymore now that RB-2.6 is the default branch.

### CODE REVIEW

**Comment by acolwell** [comment]
> There are conflicts when merging RB-2.5into RB-2.6, so I could not do a full merge. This is just a cherrypick of some of the 18 commits, but those related to:
> 
> 1. github actions
> 2. cmake
> 3. windows packages
> 
> were not merged. Here's the full list of missing commits:
> 
> * [7ddcfe8](https://github.com/NatronGitHub/Natron/commit/7ddcfe8afd1f03e428ce6cbc4f7c7737d9923838) @rodlie
> * [d1c2659](https://github.com/NatronGitHub/Natron/commit/d1c2659dda688459a7b2aeb675718c65880ffd1d) @rodlie
> * [1fe5e52](https://github.com/NatronGitHub/Natron/commit/1fe5e5281f0cb1933d099d192c8f7dc0f9b06acc) reviewed by  @acolwell
> * [c7767b1](https://github.com/NatronGitHub/Natron/commit/c7767b15044297b52737e5878d395067434bb8d5) @acolwell
> * [cc47b65](https://github.com/NatronGitHub/Natron/commit/cc47b65670df85fc9ac5e49e9a3579a5b75bbaaa) @acolwell
> * [fddb2e7](https://github.com/NatronGitHub/Natron/commit/fddb2e75dd535ae8b791aa73678ffbea9446a642) @acolwell
> * [2d14d4e](https://github.com/NatronGitHub/Natron/commit/2d14d4e04c9277db728f19b2405e3b9c234a4ab0) @acolwell
> 
> @acolwell or @rodlie could you check what needs to be merged and do a full merge of RB-2.5 into RB-2.6? We should always merge changes from RB-2.x into RB-2.y if x < y, so that RB-2.y is fully ahead of RB-2.x. Hopefully this will not be an issue anymore now that RB-2.6 is the default branch.

I merged everything from 2.5 to 2.6 before I requested 2.6 become the default branch. (https://github.com/NatronGitHub/Natron/pull/977) I believe your [MacPorts change](https://github.com/NatronGitHub/Natron/commit/42538868542be827edb8059571ab92b06e20d675) and [RotoPaint fix](https://github.com/NatronGitHub/Natron/commit/7eea73e6a0e58318c87ae00fd449679339fa2059) are the only things that actually need to be merged.

**Comment by rodlie** [comment]
Just resolve the merge issues?

Commit https://github.com/NatronGitHub/Natron/commit/73e7dd8f83a5963fa2f4ebe5e36f9827f094e799 breaks against RB-2.5, just ignore the changes coming from RB-2.5.

Also the same with the macports changes in https://github.com/NatronGitHub/Natron/commit/42538868542be827edb8059571ab92b06e20d675, but instead accept the changes from RB-2.5.

**Comment by rodlie** [comment]
This should work? https://github.com/NatronGitHub/Natron/compare/RB-2.6...rodlie:Natron:merge-RB256?expand=1

**Comment by acolwell** [comment]
> This should work? https://github.com/NatronGitHub/Natron/compare/RB-2.6...rodlie:Natron:merge-RB256?expand=1

@rodlie that looks good to me. I think I accidentally didn't do a 'merge commit' when I merged everything before so that is why we have all the commits that were merged already still showing up in this merge. I think what you have there will be a better option than this cherry pick PR because I think it will make future merges from 2.5(please no more) less painful.

Sorry for causing this issue.

**Comment by devernay** [comment]
cancelling

**Pull request closed without merging**
