### PR TITLE
Fix rotopaint overlay

### PR DESCRIPTION
**Pull request by devernay**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality nor fixes a bug but improves Natron in some way)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly

**What does this pull request do?**

With many overlay tools, the tool cursor is par of the overlay, so the overlay should always be refreshed on pen motion with these tools.

### CODE REVIEW

**Comment by acolwell** [comment]
I'm assuming that the last commit is the only thing you are actually trying to change. I suspect you may need to do something like "git rebase --onto RB-2.6 08b1c1ae9833417e1bd46b14be29916454dc4f87" and then force push to get this PR to only contain that last commit.

The changes in that last commit look ok to me. I'm not very familiar with this code, but I'm wondering if the redraw assignment around line 2770 should be modified from "redraw = " to "redraw |=" so that it doesn't accidentally cancel the value you set in your new logic.

**Comment by rodlie** [comment]
Can confirm that https://github.com/NatronGitHub/Natron/pull/982/commits/08b1c1ae9833417e1bd46b14be29916454dc4f87 fixes the broken overlay, thanks :+1:

**Comment by devernay** [comment]
> line 2770 should be modified from "redraw = " to "redraw |="

done in latest commit (I prefered explicitly setting redrew = true if necessary, for readability)

**Comment by devernay** [comment]
mmoving to a PR on RB-2.5

**Pull request closed without merging**
