### PR TITLE
Fix Windows installer build by adding missing Arena.ofx dependency

### PR DESCRIPTION
**Pull request by acolwell**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality nor fixes a bug but improves Natron in some way)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly

**What does this pull request do?**

libheif was recently updated in MSYS2 to depend on libopenjph. This change simply adds this dependency so that the installer will build again and pass its dependency checks.

**Have you tested your changes (if applicable)? If so, how?**

Yes. I verified the Windows installer [builds successfully](https://github.com/acolwell/Natron/actions/runs/9921688369) again.

### CODE REVIEW

**Review by rodlie — APPROVED** [review]

**Comment by rodlie** [comment]
btw, should probably remove heif in imagemagick/arena. It serves no purpose (OIIO should handle it), don't know why it was added in the first place.

**Comment by acolwell** [comment]
> btw, should probably remove heif in imagemagick/arena. It serves no purpose (OIIO should handle it), don't know why it was added in the first place.

Looks like you turned it on a few years ago. https://github.com/NatronGitHub/Natron/commit/c3052e988c698dab1a87442553b337ec0a513fa6

I can try turning it back off and see what happens.

**Comment by rodlie** [comment]
> Looks like you turned it on a few years ago

Yes, that was since it was enabled on Linux/Mac at some point and I just matched the depends.

Heif might have been enabled in IM for some script usage, don't know.

> I can try turning it back off and see what happens.

Nothing in openfx-arena uses or supports heif so should not break anything.

**Comment by acolwell** [comment]
> > Looks like you turned it on a few years ago
> 
> Yes, that was since it was enabled on Linux/Mac at some point and I just matched the depends.
> 
> Heif might have been enabled in IM for some script usage, don't know.
> 

I figured that was the case. I've made a change to turn it off and have started an installer build to see if anything breaks. Once that is done I'll try running Natron-Tests with that build since that test suite uses ImageMagick for image comparisons.

> > I can try turning it back off and see what happens.
> 
> Nothing in openfx-arena uses or supports heif so should not break anything.

Agreed. I'm always down for reducing unnecessary dependencies where possible. :)

**Pull request merged**
