### PR TITLE
#439 Forced hasChanged to true in call to setValue in choiceRestorati…

### PR DESCRIPTION
**Pull request by splidje**
Apologies for the previous "fix".
I haven't managed to run the tests, as I don't have them set up properly yet.
However, this change doesn't have the same problem with #447

### CODE REVIEW

**Comment by devernay** [comment]
Thanks! Can you resolve the conflict?

**Comment by devernay** [comment]
@splidje you should pull from from RB-2.3, because your previous commit was since reverted. Then you fix the conflict and push again to this branch (which you called `#439`)
```
git remote set-url origin https://github.com/NatronGitHub/Natron.git
git checkout '#439'
git pull origin RB-2.3
# resolve conflict, and commit, then...
git push
```

**Comment by splidje** [comment]
Ok, conflict is now resolved.

**Comment by devernay** [comment]
did you run the unit tests?
check frameblend.ntp?

running the unit tests is rather easy. Here's what I do on my Mac. Just change the cache and plugins location to run it on linux or win.

To run Unit tests from a snapshot, make sure that OFX plugins are not installed, and clear the cache beforehand:
```
natron="/Applications/Natron.app"
rm -rf  "$HOME/Library/Caches/INRIA/Natron"* &> /dev/null || true
rm /Library/OFX/Plugins/*
env FONTCONFIG_FILE="$natron/Contents/Resources/etc/fonts/fonts.conf" OCIO="$natron/Contents/Resources/OpenColorIO-Configs/blender/config.ocio" OFX_PLUGIN_PATH="$natron/Contents/Plugins/OFX" FFMPEG="$natron/Contents/MacOS/ffmpeg" ./runTests.sh "$natron/Contents/MacOS/NatronRenderer"
```

To run unit tests from a local build, OFX plugins must be installed (on Unix I think the location is /usr/OFX/Plugins):
```
natron="$HOME/Development/Natron-2.3/App/build/Debug/Natron.app"
(cd /Library/OFX/Plugins && rm * && ln -s ../Natron-release/* .)
rm -rf  "$HOME/Library/Caches/INRIA/Natron"* &> /dev/null || true
env FONTCONFIG_FILE="$natron/../../../../Gui/Resources/etc/fonts/fonts.conf" OCIO="$natron/../../../../OpenColorIO-Configs/blender/config.ocio" OFX_PLUGIN_PATH="/Library/OFX/Plugins" NATRON_PLUGIN_PATH="$natron/../../../../Gui/Resources/PyPlugs" FFMPEG="ffmpeg" ./runTests.sh "$natron/../../../../Renderer/build/Debug/NatronRenderer"
```

**Pull request merged**
