### PR TITLE
System libs for glog and Ceres in CMake

### PR DESCRIPTION
**Pull request by YakoYakoYokuYoku**
## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [x] New feature (non-breaking change which adds functionality)

**What does this pull request do?**

Because a system installation of glog may conflict with the bundled version (see #807) and Ceres can take quite the time to build, I've decided to provide the option to use the system version for the CMake build. openMVG was ignored due to not many distributions provide a package for it and its lack of CMake config files for the build to discover its install, though this can be revisited in the future.

**Show a few screenshots (if this is a visual change)**

N/A.

**Have you tested your changes (if applicable)? If so, how?**

By building with those libraries and running Natron.

**Futher details of this pull request**

In the future, when Qt6 support arrives alongside the official HTTP server module, qhttpserver will receive the same treatment.

### CODE REVIEW

**Comment by devernay** [comment]
hum I don't think this is a good idea.
We're using an older version of Ceres, and we may be lagging on glog too. Current versions are untested. It's better to stick with what we provide until the current versions are properly tested.
The problem with a system installation of glog or ceres can be fixed by making sure the include path and the library path are correctly set. I would prefer that.

**Comment by YakoYakoYokuYoku** [comment]
Happens that I cannot commit directly to protected branches as of now so that's why I need somebody else with that kind of permissions.

**Comment by YakoYakoYokuYoku** [comment]
> We're using an older version of Ceres, and we may be lagging on glog too. Current versions are untested. It's better to stick with what we provide until the current versions are properly tested.
> The problem with a system installation of glog or ceres can be fixed by making sure the include path and the library path are correctly set. I would prefer that.

In my case I can say that current versions of Ceres and glog work with Natron in Arch Linux. But if issues raise from using the system installs then the bundled versions can comfortably be used instead, and due to the lack of testing in platforms different than Linux then it makes sense that the option is `OFF` by default as this PR does.

**Comment by devernay** [comment]
Ok to keep it OFF, but does this also fix #807 if there are system versions installed?

**Comment by YakoYakoYokuYoku** [comment]
I speculate that given the option to not use the bundled version of glog it would not pass any include or link flags that collide with the ones from a system install, but we have to take in consideration that QMake was being in use in that issue, which links glog as `-lglog` (as of time of writing of said issue CMake wasn't supported yet) and that CMake is a fix too, due to its nature that project libraries are linked using their path directly, i.e. glog would be linked with `build/glog/libglog.a` instead of `-lglog`, thus disambiguating between a bundled version and a system version of glog, same as openMVG or libmv.

**Comment by YakoYakoYokuYoku** [comment]
Merging this PR in the evening if there are no further objections.

**Review by devernay — APPROVED** [review]

**Pull request merged**
