### PR TITLE
Documentation Write node

### PR DESCRIPTION
**Pull request by bonalex01dev**
Documentation of the write node
changes in the interlinking of the related pages

pages to review:
https://natron--625.org.readthedocs.build/en/625/guide/thenodes-image-write.html
https://natron--625.org.readthedocs.build/en/625/guide/compositing-projects-render.html
https://natron--625.org.readthedocs.build/en/625/guide/getstarted-environment-nodegraph.html
https://natron--625.org.readthedocs.build/en/625/guide/getstarted-environment-nodes.html

### CODE REVIEW

**Comment by bonalex01dev** [comment]
Nodes and Nodegraph also documented commit #626

**Comment by devernay** [comment]
https://natron--625.org.readthedocs.build/en/625/guide/thenodes-image-write.html
https://natron--625.org.readthedocs.build/en/625/guide/compositing-projects-render.html
https://natron--625.org.readthedocs.build/en/625/guide/getstarted-environment-nodegraph.html
https://natron--625.org.readthedocs.build/en/625/guide/getstarted-environment-nodes.html

**Review by devernay — APPROVED** [review]
thanks for this large contribution.
we need people to do doc reviews, so please try to edit your PR description to add direct links to the pages to review on rtfd, as I did in the comment. It helps a lot! And make a call for reviews on pixls.us. we can add Doc reviewers to the github project if they want.
https://natron--625.org.readthedocs.build/en/625/guide/thenodes-image-write.html
https://natron--625.org.readthedocs.build/en/625/guide/compositing-projects-render.html
https://natron--625.org.readthedocs.build/en/625/guide/getstarted-environment-nodegraph.html
https://natron--625.org.readthedocs.build/en/625/guide/getstarted-environment-nodes.html

**Comment by bonalex01dev** [comment]
I discovered Blender doc  guidelines forbids animated GIFs because:
- GIF is not free software
- The doc should be printable.
Do we want to obey such strict guidelines ? Or am I too enthusiastic because I just discovered how to make animated GIFs ?

**Comment by devernay** [comment]
I was concerned about this initially, but I guess not many people print the docs or read these.
Alternatively, we could also have a printable (non-animated) illustration for each of these, so if you have a single non-animated image that can be used for the printed version, please add it to the repo (with a different filename).

See here how we can use different images for the web and print version.
I wonder, if we have both gnu.gif and gnu.png, will `.. image:: gnu.* ` include the gif for the web version and the png for the print version?
https://stackoverflow.com/questions/6473660/using-sphinx-docs-how-can-i-specify-png-image-formats-for-html-builds-and-pdf-im

**Comment by devernay** [comment]
ah and btw GIF is now patent-free and can be used freely. See the first paragraph of https://www.gnu.org/philosophy/gif.html

**Comment by bonalex01dev** [comment]
OK, I'll try to to go the dual format route. Thanks for looking into it

**Comment by rodlie** [comment]
My only concern regarding GIF is the quality, usually looks bad (256 colors!) and takes up a lot of space (compared to the quality).

This looks interesting: https://github.com/sphinx-contrib/video

Use a webm/mp4 and fallback to a png.

**Comment by bonalex01dev** [comment]
Ok I will look into video integration. Will prove useful for longer tips anyway.
Anyhow I keep on reducing the gif number of frames to a bare minimum

I have to (correct me if Im wrong):
- edit conf.py in the source to enable extension on my machine and readthedocs compiler
- install the extension files on my machine ( with pip in my python path ?)
- - install the extension files on the read the docs compiler ( but how ?)

**Comment by rodlie** [comment]
> Ok I will look into video integration.

No rush, just continue with the gif's, we can look at video integration later.

**Pull request merged**
