### PR TITLE
GitHub Action for building Windows installers

### PR DESCRIPTION
**Pull request by acolwell**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which does not add functionality nor fixes a bug but improves Natron in some way)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly

**What does this pull request do?**

It creates a GitHub Action that builds a normal Windows installer and Windows Installer that has Breakpad crash reporting enabled. Some of the build scripts needed to be modified to reduce the installer build disk usage. Without these changes the build runs out of disk space on the runner and fails.

**Have you tested your changes (if applicable)? If so, how?**

Yes. I've been running this action in my Natron fork for the last week or two and use it to create nightly installer builds.

### CODE REVIEW

**Review by devernay — APPROVED** [review]
Nice! Thank you!
LGTM (new build feature)

**Comment by devernay** [comment]
Doesn't it require InnoSetup as mentioned here https://github.com/NatronGitHub/Natron/pull/901#issuecomment-1707121073 ?
Or maybe it only builds the zip versions?

**Comment by rodlie** [comment]
> Doesn't it require InnoSetup as mentioned here https://github.com/NatronGitHub/Natron/pull/901#issuecomment-1707121073 ?

Inno is only needed when building the mingw-natron-setup package. Setup.exe only needs to be built on changes in PKGBUILD/Natron.iss.

https://github.com/NatronGitHub/Natron/tree/RB-2.5/tools/MINGW-packages/mingw-w64-natron-setup

**Comment by rodlie** [comment]
Btw, we need to add `[InstallDelete]` to the Natron.iss file, or else we might breaks installations during major upgrades (Py/Qt).

**Comment by acolwell** [comment]
> > Doesn't it require InnoSetup as mentioned here [#901 (comment)](https://github.com/NatronGitHub/Natron/pull/901#issuecomment-1707121073) ?
> 
> Inno is only needed when building the mingw-natron-setup package. Setup.exe only needs to be built on changes in PKGBUILD/Natron.iss.
> 
> https://github.com/NatronGitHub/Natron/tree/RB-2.5/tools/MINGW-packages/mingw-w64-natron-setup

@rodlie is right. Inno is only needed for mingw-w64-natron-setup package creation. Sorry for the confusion.

**Comment by acolwell** [comment]
> Btw, we need to add `[InstallDelete]` to the Natron.iss file, or else we might breaks installations during major upgrades (Py/Qt).

Is this so you can install over the top of an existing install instead of uninstalling? If you uninstall the old version and install the new version it should work ok. Is that correct? I'm just trying to understand it issue here.

**Comment by rodlie** [comment]
> Is this so you can install over the top of an existing install instead of uninstalling?

Inno does not remove anything before install. If you have Natron 2.5.0 and upgrade to 2.6.0 you might end up with issues because you have leftover files from 2.5.0 that could interfere with you new installation.

So we should have a list of files/dirs that must be removed prior to install/upgrade.

```
[InstallDelete]
...
```

> If you uninstall the old version and install the new version it should work ok

Yes

**Pull request merged**
