### PR TITLE
Engine/CLArgs.cpp: allow dot in writer name

### PR DESCRIPTION
**Pull request by rodlie**
Allow access to writers in a group, see https://discuss.pixls.us/t/rendering-nested-write-nodes/33225

Tested on Windows 11 (``NatronRenderer project.ntp -w Group1.Write1``).

### CODE REVIEW

**Review by devernay — APPROVED** [review]

**Comment by devernay** [comment]
@rodlie would you be ready for a 2.4.4 release?

**Comment by devernay** [comment]
(python 2.7)

**Comment by rodlie** [comment]
Yes, I have a dedicated machine for building RB-2.4, but I have not updated the SDK in a while (OIIO etc).

**Comment by devernay** [comment]
I think that's ok, the goal is to fix bugs and bring the few new features.
OIIO and ffmpeg updates may be valuable, but not necessary.

**Comment by rodlie** [comment]
Ok, it will then be built against the same SDK as v2.4.3. The machine is up and running.

**Comment by rodlie** [comment]
BayMax test fails compared to 2.4.3, will need to figure out why.
```
@@ -195,7 +195,7 @@
 TestVectorToColor : PASS
 TestWave : PASS
 TestZMask : PASS
-BayMax : PASS
+BayMax : FAIL
 GNUVolador : PASS
 Spaceship : PASS
 TestCMD/WriteOIIO1 : PASS
```

Ref:
BayMax-reference8
Out:
BayMax-output8
Diff:
BayMax-comp8

**Comment by rodlie** [comment]
So, it's not a problem with the SDK, as building v2.4.3 results in BayMax PASS.

**Comment by devernay** [comment]
that was a hard one!

culprid: https://github.com/NatronGitHub/openfx-io/pull/23

since YRotate and XRotate don't have the same defaults, this changed the SeNoise default behavior.

Fix:
https://github.com/NatronGitHub/openfx-io/commit/a0fa5d734c7a96776ee56828a4b3fcf895f09976

**Comment by rodlie** [comment]
Great 👍 

Just got to work, but will remote in to the machine and start a new build.

I upgraded OIIO from 2.3.11 to 2.3.21 and FFmpeg from 4.4. to 4.4.3. I will not go beyond OIIO 2.3.x and FFmpeg 4.4.x for RB-2.4 (to keep compatibility and don't introduce new issues).

**Pull request merged**
