### PR TITLE
Fix typos in Engine/

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -i 3 -w -S *.svg -L ba,originaly,datas,uint,heros,lod`

### CODE REVIEW

**Comment by luzpaz** [comment]
@devernay there are more instances of `thread local storage` then just the above, within `Engine/`. Shall I change those as well ?

**Comment by devernay** [comment]
Yes, thanks!

**Comment by luzpaz** [comment]
Done in 03e4cce

**Comment by devernay** [comment]
will merge as soon as the travis check is OK

**Pull request merged**
