### PR TITLE
Add version tags, oars and screenshot

### PR DESCRIPTION
**Pull request by nedrichards**
Sample improved appdata for #281 *however* the screenshot currently in place is far too low res - better screenshots need to be in place before this should be merged.

### CODE REVIEW

**Comment by nedrichards** [comment]
@Sunderland93 great idea. updated the patch with that link.

**Comment by Sunderland93** [comment]
@nedrichards Hi. Please update screenshot with Wikimedia link https://upload.wikimedia.org/wikipedia/commons/c/cc/Natron-screenshot-20180619.png and change Natron's site from natron.fr to https://https://natrongithub.github.io . Thanks

**Comment by Sunderland93** [comment]
@devernay can you please merge this PR? It very necessary for Flatpak users, for example. For now Natron on Flathub doesn't have screenshot and additional info https://flathub.org/apps/details/fr.natron.Natron

**Comment by devernay** [comment]
done!

**Comment by Sunderland93** [comment]
@devernay you close this, but not merge...

**Pull request merged**
