### PR TITLE
Documentation: make sure theme is found

### PR DESCRIPTION
**Pull request by rodlie**
On CentOS (build server) the sphinx_rtd_theme is not found, this fixes it.

### CODE REVIEW

**Comment by devernay** [comment]
I think it would be better to just add `pip install sphinx_rtd_theme` to the SDK.
The newest version of the sphinx doc doesn't recommend this method:
https://sphinx-rtd-theme.readthedocs.io/en/latest/installing.html#via-python-package

The last version that recommended this is 0.2.5b2: https://pypi.org/project/sphinx-rtd-theme/0.2.5b2/

And the current version is 0.4.3.

Do you agree that doing the right pip install is the right solution?

**Comment by rodlie** [comment]
That's also an option, then sphinx etc must be installed through python built from the SDK? I'm currently using system packages for sphinx on CentOS6 to avoid bloating python in the SDK.

**Comment by devernay** [comment]
That's probably a very old version of Sphinx.  Sphinx is already installed by Sphinx rtd theme in SDK, but I'll make it a separate package

**Comment by rodlie** [comment]
I used v1.3 or something, the html and pdf looks ok but there might be some bugs somewhere.

**Comment by devernay** [comment]
We don't build the PDF (it is available from https://natron.readthedocs.io ).

Everything used to build Natron should come from the SDK only. We only use the a few utilities from the system to bootstrap the SDK build (`gcc g++ make wget tar patch find gzip` see line 207 of build-Linux-sdk.sh)

The goal is to get consistent and repeatable builds.

**Comment by devernay** [comment]
Closing: sphinx and sphinx_rtd_theme are now part of the sdk.
see https://github.com/NatronGitHub/Natron/commit/bac2ae1995021b60c97f8861a80deeba9d9d034d  and https://github.com/NatronGitHub/Natron/commit/f7be30fd706f37b8c17cecd0ebcb436cd33e1eaf

**Pull request closed without merging**
