### PR TITLE
Fix typos in Documentation/ 

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./libs/google-breakpad -L iff,lod,pard,uint`

### CODE REVIEW

**Comment by luzpaz** [comment]
Note: I made sure to keep the format of of the `.rst` ascii boxes

**Comment by devernay** [comment]
Nice! Thank you!
The problem is that the plugins doc is generated from the plugins source. Can you please make a PR with everything except the plugins doc?
Would you fix the plugins doc by doing a PR on each plugin repo? If not, can you please do a PR with just the plugins doc? We'll use that as a reference and fix the plugin sources when we have time.

**Comment by luzpaz** [comment]
> The problem is that the plugins doc is generated from the plugins source. Can you please make a PR with everything except the plugins doc?
> Would you fix the plugins doc by doing a PR on each plugin repo? If not, can you please do a PR with just the plugins doc? We'll use that as a reference and fix the plugin sources when we have time.

Can you literally explain which directories you want me to avoid ?

**Comment by devernay** [comment]
See https://natron.readthedocs.io/en/rb-2.3/guide/tutorials-writedoc.html#writing-contributions :
"The following files are generated automatically and can thus not be edited:

    The _group.rst file, and any file with a name starting with _group.
    The _prefs.rst.
    The documentation for each individual plugin, which can be found in the Documentation/source/plugins directory"

**Comment by devernay** [comment]
And feel free to make similar PRs on the following repos:
- openfx-misc
- openfx-io
- openfx-gmic
- openfx-arena

**Pull request closed without merging**
