### PR TITLE
Generate Python bindings with PySide2 5.15.4

### PR DESCRIPTION
**Pull request by YakoYakoYokuYoku**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [x] Breaking change (fix or feature that would cause existing functionality to change)

**What does this pull request do?**

Version 5.15.4 of PySide2 has some incompatibilities with previous versions, for instance the absence of the `qapp_macro.h` header. Compiling Natron with it results in failure, so this PR has the generated sources for this release.

**Show a few screenshots (if this is a visual change)**

N/A.

**Have you tested your changes (if applicable)? If so, how?**

By building and running Natron.

**Futher details of this pull request**

This might or might not work with previous PySide2 releases, so if you are using them check this PR out or revert this change in case of merge.

### CODE REVIEW

**Comment by rodlie** [comment]
So, this will break compatibility with previous PySide2/Qt 5.15 (and older) releases? What are we compatible with before this commit? (IMHO we should try to be compatible with 5.12-5.15, within reason).

**Comment by YakoYakoYokuYoku** [comment]
I did not test with previous releases so I can't tell and before this commit we were compatible with at least PySide2 5.15.2. But I'm against to provide support with versions previous to Qt 5.15 as all of them have been discontinued (see [Qt 5.12.12](https://www.qt.io/blog/qt-5.12.12-released)) and Qt 5.15 is the only version of Qt5 that has open source releases and still being worked on (either officially or in the KDE forks) due to the new Qt licensing of LTS.

**Comment by devernay** [comment]
PySide 5.15.3 also requires this

**Comment by devernay** [comment]
The linux docker build image has [PySide2 5.15.2.1 installed through pip](https://pypi.org/project/PySide2/).
We need to check if this PR builds with it.

**Comment by YakoYakoYokuYoku** [comment]
> PySide 5.15.3 also requires this

There's #803 for generating Python bindings inside QMake 5.15 and I prefer that over this PR (QMake 4 seems to not cooperate with it though it works just fine with the in repo sources).

**Comment by rodlie** [comment]
Ubuntu 22.04 has Qt 5.15.3, but uses PySide 5.15.2. So this might break there, can check.

EDIT: Yes, it breaks on Ubuntu 22.04.

> There's https://github.com/NatronGitHub/Natron/pull/803 for generating Python bindings inside QMake 5.15 and I prefer that over this PR

Probably a good idea for Qt5.

**Comment by YakoYakoYokuYoku** [comment]
Well I'll go forward with #803, closing then.

**Pull request closed without merging**
