### PR TITLE
Renovate QWheelEvent in Gui

### PR DESCRIPTION
**Pull request by YakoYakoYokuYoku**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality nor fixes a bug but improves Natron in some way)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly

**What does this pull request do?**

`QWheelEvent` has many [deprecated members in Qt 5](https://doc.qt.io/qt-5/qwheelevent-obsolete.html) and usages like deltas, horizontal scrolls or positions are replaced with methods that returns `QPoint`s that hold the relevant values.

**Show a few screenshots (if this is a visual change)**

N/A.

**Have you tested your changes (if applicable)? If so, how?**

Built Natron and used the node graph editor.

**Futher details of this pull request**

N/A.

### CODE REVIEW

**Review by devernay — APPROVED** [review]

**Comment by devernay** [comment]
What OS are you testing this on? Are you also testing on a laptop with a multi-touch trackpad that allows scrolling (for testing the wheel events)

**Comment by devernay** [comment]
Also, are you testing the Qt5 version on a hiDPI display? linux, mac, windows? I had to fix something for retina on macOS, and wanted to be sure it didn't break others.
BTW we may have to release a 2.6 alpha with Qt5 soon, at least on macOS, because Qt4 is invariably crashing on macOS Monterey

**Comment by YakoYakoYokuYoku** [comment]
I'm testing this on Solus, a Linux desktop distro. At the moment I'm with my PC tower only so I cannot test with a laptop. Also my monitor DPI has 96 dots per inch so no validations with hiDPI either.

**Comment by YakoYakoYokuYoku** [comment]
If we want to release an alpha sooner I'll start volleying other commits that I have in my local branch.

**Pull request merged**
