### PR TITLE
[help] natron: support for qt6

### PR DESCRIPTION
**Pull request by Martinfx**
Thanks for submitting a pull request! Please provide enough information so that others can review your pull request. Additionally, make sure you've done all of these things:

- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CODE_OF_CONDUCT.md) to the best of my understanding
- [x] I've read and understood the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md)
- [x] I've formatted my code according to Natron's [code style]([#](https://github.com/NatronGitHub/Natron#logistics))
- [x] I've searched the [pull requests tracker](https://github.com/NatronGitHub/Natron/pulls?q=is%3Apr) to ensure that this PR is not a duplicate

## PR Description

**What type of PR is this? (Check one of the boxes below)**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality nor fixes a bug but improves Natron in some way)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
    - [ ] I have updated the documentation accordingly

**What does this pull request do?**
Enable support for QT6

[Your answer, explain the motivation for making this change.]
qt5 will be at the end of its life

**Show a few screenshots (if this is a visual change)**

[Your answer, delete this section if it is not a visual change.]

**Have you tested your changes (if applicable)? If so, how?**
I tested on FreeBSD now but there are some errors.

1. clone this branch 
2. cmake ..

[Your answer]

**Futher details of this pull request**

[Your answer]

### CODE REVIEW

**Comment by Martinfx** [comment]
```
FAILED: libs/qhttpserver/CMakeFiles/qhttpserver.dir/qhttpserver_autogen/mocs_compilation.cpp.o 
/usr/bin/c++ -DDEBUG -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -I/usr/home/maxfx/Documents/FreeBSD-Ports/natron/work/.build/libs/qhttpserver/qhttpserver_autogen/include -I/usr/home/maxfx/Documents/FreeBSD-Ports/natron/work/Natron-2.5.1-pre2/libs/qhttpserver/http-parser -isystem /usr/local/include/qt6/QtCore -isystem /usr/local/include/qt6 -isystem /usr/local/lib/qt6/mkspecs/freebsd-clang -isystem /usr/local/include/qt6/QtNetwork -pipe -g -fstack-protector-strong -fno-strict-aliasing -pipe -g -fstack-protector-strong -fno-strict-aliasing -std=gnu++17 -fPIC -Wall -Wextra -Wmissing-declarations -Wno-multichar -Winit-self -Wno-long-long -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -Wno-deprecated-copy -fPIC -pthread -MD -MT libs/qhttpserver/CMakeFiles/qhttpserver.dir/qhttpserver_autogen/mocs_compilation.cpp.o -MF libs/qhttpserver/CMakeFiles/qhttpserver.dir/qhttpserver_autogen/mocs_compilation.cpp.o.d -o libs/qhttpserver/CMakeFiles/qhttpserver.dir/qhttpserver_autogen/mocs_compilation.cpp.o -c /usr/home/maxfx/Documents/FreeBSD-Ports/natron/work/.build/libs/qhttpserver/qhttpserver_autogen/mocs_compilation.cpp
warning: unknown warning option '-Wshift-overflow=2'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
In file included from /usr/home/maxfx/Documents/FreeBSD-Ports/natron/work/.build/libs/qhttpserver/qhttpserver_autogen/mocs_compilation.cpp:3:
/usr/home/maxfx/Documents/FreeBSD-Ports/natron/work/.build/libs/qhttpserver/qhttpserver_autogen/UVLADIE3JM/moc_qhttprequest.cpp:227:52: error: conversion from 'HttpMethod' to 'QChar' is ambiguous
  227 |         case 3: *reinterpret_cast< QString*>(_v) = _t->method(); break;
      |                                                    ^~~~~~~~~~~~
/usr/local/include/qt6/QtCore/qchar.h:76:26: note: candidate constructor
   76 |     constexpr Q_IMPLICIT QChar(ushort rc) noexcept : ucs(rc) {}
      |                          ^
/usr/local/include/qt6/QtCore/qchar.h:78:26: note: candidate constructor
   78 |     constexpr Q_IMPLICIT QChar(short rc) noexcept : ucs(char16_t(rc)) {}
      |                          ^
/usr/local/include/qt6/QtCore/qchar.h:83:26: note: candidate constructor
   83 |     constexpr Q_IMPLICIT QChar(char16_t ch) noexcept : ucs(ch) {}
      |                          ^
/usr/local/include/qt6/QtCore/qchar.h:612:5: note: candidate constructor has been explicitly deleted
  612 |     QChar(char c) = delete;
      |     ^
/usr/local/include/qt6/QtCore/qchar.h:613:5: note: candidate constructor has been explicitly deleted
  613 |     QChar(uchar c) = delete;
      |     ^
/usr/local/include/qt6/QtCore/qstring.h:177:30: note: passing argument to parameter 'c' here
  177 |     QString &operator=(QChar c);
      |                              ^
3 warnings and 1 error generated.

```

**Comment by devernay** [comment]
@acolwell can you sync with @Martinfx on Qt6 support? I think you were also working on this? May be this should be on a separate branch (RB-2.7?) since we haven't yet released Natron 2.6 with Qt5.

**Comment by rodlie** [comment]
> May be this should be on a separate branch (RB-2.7?) since we haven't yet released Natron 2.6 with Qt5.

Agree.

IMHO RB-2.6 should stay on Qt 5.15 (maintained by upstream until 2026, also maintained in EL9 until 2032), so I see no rush to move to Qt6 on the "stable" branch.

**Comment by YakoYakoYokuYoku** [comment]
Thanks for the PR it's really appreciated. Though, I've made #1019 which is a tad bit better in some aspects and relatively more future-proof, feel free to check it out.

**Comment by Martinfx** [comment]
> Thanks for the PR it's really appreciated. Though, I've made #1019 which is a tad bit better in some aspects and relatively more future-proof, feel free to check it out.

ok i can #1019 test on freebsd ?

**Comment by YakoYakoYokuYoku** [comment]
You are encouraged to do so.

**Comment by Martinfx** [comment]
> You are encouraged to do so.

ok. i close this bug and i will use #1019.

**Pull request closed without merging**
