### PR TITLE
Stylesheet

### PR DESCRIPTION
**Pull request by fcocc77**
I made a design change, but I deleted many things from the project to make it easier for me and I made some scripts for only for centos 7 for me, ignore them, what matters is the stylesheet folder and the Gui folder that modifies some name "setObjectName" to be able to separate the components of the gui, I made the design with sass which is a css precompiler, see if you can rescue it, I will continue correcting it, when I have time. my whatsap in case you have any questions +56938901513, hopefully you can integrate it, because I am interested in natron for my personal project.

## Description
- Change the entire design (https://we.tl/t-wHLsWfkYR3)
- Correction of some ugly blinks
- Limit the viewer's combobox to 3 digits

general
progress
scripts
settings
curveditor
dialog

### CODE REVIEW

**Comment by rodlie** [comment]
We can't accept this. Please do a new pull request with only the style(sheet) changes.

**Comment by fcocc77** [comment]
If I know that they cannot accept it, it was in case they wanted to extract it manually.

**Comment by fcocc77** [comment]
when I have time I do another clean pull request, regards

**Comment by Songtech-0912** [comment]
@fcocc77 I will try to clean up your stylesheet and design changes in my fork, if you're ok with that.

**Comment by vinavfx** [comment]
ok

**Comment by Songtech-0912** [comment]
Because I don't think this issue will get resolved anytime soon and because it's a bit too hard to clean up (for marginal gains), I think we should close this PR.

**Comment by vinavfx** [comment]
Yes, I agree.

**Review by h3adband — APPROVED** [review]

**Comment by rodlie** [comment]
Thanks for your PR, but for obvious reasons we can't merge this. Feel free to do another one (we can merge) at some point :)

**Pull request closed without merging**
