### PR TITLE
Engine: fix return value in Project::isGraphWorthLess()

### PR DESCRIPTION
**Pull request by rodlie**
Issue #217

### CODE REVIEW

**Comment by devernay** [comment]
I don't understand your fix. It means that if a project was auto-saved and was manually saved, then it's worthless?

**Comment by rodlie** [comment]
If isGraphWorthLess is true means it's saved (or has no nodes), we can then open the new project in this instance. If isGraphWorthLess is false means it's not saved (or has nodes), we must then open the new project in a new instance.

Isn't that's how it's supposed to work?

**Comment by devernay** [comment]
worthless means it has no value and can be thrown away.

Read the comment above: "If it has never auto-saved, then the user didn't do anything, hence the project is worthless."

What should be added is the fact that any modification was made to the project since it was created or loaded.

I think the problem is that the first modification (such as adding a node to an empty project) doesn't trigger an auto-save  - to be verified - so the first part of the test `( !hasEverAutoSaved() && !hasProjectBeenSavedByUser() )` is true, thus the project is considered worthless and is thrown away.

The project should only be considered worthless if there was no single edit since the project was loaded or created, or if it is empty (ie !hasNodes()). The first part is thus wrong in the code.

**Comment by rodlie** [comment]
Ok, will do some more checks tomorrow.

**Pull request closed without merging**
